export const statusClassMap = new Map()
  .set('0', 'to-status-style')
  .set('1', 'do-status-style')
  .set('2', 'finish-status-style')
export const tagsClassMap = new Map()
  .set('save', 'save-tags-style')
  .set('order', 'order-tags-style')
export const statusTextMap = new Map().set('0', '待计划').set('1', '已计划').set('2', '已完结')
export const tagsTextMap = new Map().set('save', '库存计划').set('order', '订单计划')
